/*
 * Huobi API
 *
 * Huobi API
 *
 * API version: 0.1
 * Contact: qishiwenjun@163.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package huobiapi
// InlineResponse2003 struct for InlineResponse2003
type InlineResponse2003 struct {
	Data ModelsMarketStatus `json:"data,omitempty"`
	ModelsResponse ModelsResponse `json:"models.Response,omitempty"`
}
