/*
 * Huobi API
 *
 * Huobi API
 *
 * API version: 0.1
 * Contact: qishiwenjun@163.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package huobiapi
// InlineResponse2004 struct for InlineResponse2004
type InlineResponse2004 struct {
	Data ModelsCurrency `json:"data,omitempty"`
	ModelsResponse ModelsResponse `json:"models.Response,omitempty"`
}
