/*
 * Huobi API
 *
 * Huobi API
 *
 * API version: 0.1
 * Contact: qishiwenjun@163.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package huobiapi
// InlineResponse2002 struct for InlineResponse2002
type InlineResponse2002 struct {
	Data []ModelsSymbol `json:"data,omitempty"`
	ModelsResponseV1 ModelsResponseV1 `json:"models.ResponseV1,omitempty"`
}
