/*
 * Huobi API
 *
 * Huobi API
 *
 * API version: 0.1
 * Contact: qishiwenjun@163.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package huobiapi
// ModelsPage struct for ModelsPage
type ModelsPage struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	TimeZone string `json:"time_zone,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
	Url string `json:"url,omitempty"`
}
