/*
 * Huobi API
 *
 * Huobi API
 *
 * API version: 0.1
 * Contact: qishiwenjun@163.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package huobiapi
// ModelsSummary struct for ModelsSummary
type ModelsSummary struct {
	Components []ModelsComponent `json:"components,omitempty"`
	Incidents []ModelsIncident `json:"incidents,omitempty"`
	Page ModelsPage `json:"page,omitempty"`
	ScheduledMaintenances []ModelsScheduledMaintenance `json:"scheduled_maintenances,omitempty"`
	Status ModelsSystemStatus `json:"status,omitempty"`
}
