/*
 * Huobi API
 *
 * Huobi API
 *
 * API version: 0.1
 * Contact: qishiwenjun@163.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package huobiapi
// ModelsCurrency struct for ModelsCurrency
type ModelsCurrency struct {
	Chains []ModelsChain `json:"chains,omitempty"`
	Currency string `json:"currency,omitempty"`
	InstStatus string `json:"instStatus,omitempty"`
}
