/*
 * Huobi API
 *
 * Huobi API
 *
 * API version: 0.1
 * Contact: qishiwenjun@163.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package huobiapi
// ModelsChain struct for ModelsChain
type ModelsChain struct {
	BaseChain string `json:"baseChain,omitempty"`
	BaseChainProtocol string `json:"baseChainProtocol,omitempty"`
	Chain string `json:"chain,omitempty"`
	DepositStatus string `json:"deposit_status,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	IsDynamic bool `json:"isDynamic,omitempty"`
	MaxTransactFeeWithdraw float32 `json:"maxTransactFeeWithdraw,omitempty"`
	MaxWithdrawAmt float32 `json:"maxWithdrawAmt,omitempty"`
	MinDepositAmt float32 `json:"minDepositAmt,omitempty"`
	MinTransactFeeWithdraw float32 `json:"minTransactFeeWithdraw,omitempty"`
	MinWithdrawAmt float32 `json:"minWithdrawAmt,omitempty"`
	NumOfConfirmations int32 `json:"numOfConfirmations,omitempty"`
	NumOfFastConfirmations int32 `json:"numOfFastConfirmations,omitempty"`
	TransactFeeRateWithdraw float32 `json:"transactFeeRateWithdraw,omitempty"`
	TransactFeeWithdraw float32 `json:"transactFeeWithdraw,omitempty"`
	WithdrawFeeType string `json:"withdrawFeeType,omitempty"`
	WithdrawPrecision int32 `json:"withdrawPrecision,omitempty"`
	WithdrawQuotaPerDay float32 `json:"withdrawQuotaPerDay,omitempty"`
	WithdrawQuotaPerYear float32 `json:"withdrawQuotaPerYear,omitempty"`
	WithdrawQuotaTotal float32 `json:"withdrawQuotaTotal,omitempty"`
	WithdrawStatus string `json:"withdrawStatus,omitempty"`
}
