/*
 * Huobi API
 *
 * Huobi API
 *
 * API version: 0.1
 * Contact: qishiwenjun@163.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package huobiapi
// ModelsSymbol struct for ModelsSymbol
type ModelsSymbol struct {
	AmountPrecision int32 `json:"amount-precision,omitempty"`
	BaseCurrency string `json:"base-currency,omitempty"`
	BuyMarketMaxOrderValue float32 `json:"buy-market-max-order-value,omitempty"`
	ChargeTime string `json:"charge-time,omitempty"`
	InitNav float32 `json:"init-nav,omitempty"`
	LeverageRatio float32 `json:"leverage_ratio,omitempty"`
	LimitOrderMaxOrderAmt float32 `json:"limit-order-max-order-amt,omitempty"`
	LimitOrderMinOrderAmt float32 `json:"limit-order-min-order-amt,omitempty"`
	MaxOrderAmt float32 `json:"max-order-amt,omitempty"`
	MaxOrderValue float32 `json:"max-order-value,omitempty"`
	MgmtFeeRate float32 `json:"mgmt-fee-rate,omitempty"`
	MinOrderAmt float32 `json:"min-order-amt,omitempty"`
	MinOrderValue float32 `json:"min-order-value,omitempty"`
	PricePrecision int32 `json:"price-precision,omitempty"`
	QuoteCurrency string `json:"quote-currency,omitempty"`
	RebalThreshold float32 `json:"rebal-threshold,omitempty"`
	RebalTime string `json:"rebal-time,omitempty"`
	SellMarketMinOrderAmt float32 `json:"sell-market-min-order-amt,omitempty"`
	SellMarketMaxOrderAmt float32 `json:"sell_market_max_order_amt,omitempty"`
	State string `json:"state,omitempty"`
	Symbol string `json:"symbol,omitempty"`
	SymbolPartition string `json:"symbol-partition,omitempty"`
	Underlying string `json:"underlying,omitempty"`
	ValuePrecision int32 `json:"value-precision,omitempty"`
}
