/*
 * Huobi API
 *
 * Huobi API
 *
 * API version: 0.1
 * Contact: qishiwenjun@163.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package huobiapi
// ModelsIncidentUpdate struct for ModelsIncidentUpdate
type ModelsIncidentUpdate struct {
	AffectedComponents []ModelsAffectedComponent `json:"affected_components,omitempty"`
	Body string `json:"body,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	CustomTweet map[string]interface{} `json:"custom_tweet,omitempty"`
	DeliverNotifications bool `json:"deliver_notifications,omitempty"`
	DisplayAt string `json:"display_at,omitempty"`
	Id string `json:"id,omitempty"`
	IncidentId string `json:"incident_id,omitempty"`
	Status string `json:"status,omitempty"`
	TweetId string `json:"tweet_id,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
