/*
 * Huobi API
 *
 * Huobi API
 *
 * API version: 0.1
 * Contact: qishiwenjun@163.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package huobiapi
// ModelsMarketStatus struct for ModelsMarketStatus
type ModelsMarketStatus struct {
	Code int32 `json:"code,omitempty"`
	Data ModelsMarketStatusData `json:"data,omitempty"`
	Message string `json:"message,omitempty"`
}
