/*
 * Huobi API
 *
 * Huobi API
 *
 * API version: 0.1
 * Contact: qishiwenjun@163.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package huobiapi
// ModelsAffectedComponent struct for ModelsAffectedComponent
type ModelsAffectedComponent struct {
	Code string `json:"code,omitempty"`
	Name string `json:"name,omitempty"`
	NewStatus string `json:"new_status,omitempty"`
	OldStatus string `json:"old_status,omitempty"`
}
