/*
 * Huobi API
 *
 * Huobi API
 *
 * API version: 0.1
 * Contact: qishiwenjun@163.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package huobiapi
// ModelsMarketStatusData struct for ModelsMarketStatusData
type ModelsMarketStatusData struct {
	AffectedSymbols string `json:"affectedSymbols,omitempty"`
	HaltEndTime int32 `json:"haltEndTime,omitempty"`
	HaltReason int32 `json:"haltReason,omitempty"`
	HaltStartTime int32 `json:"haltStartTime,omitempty"`
	MarketStatus int32 `json:"marketStatus,omitempty"`
}
