/*
 * Huobi API
 *
 * Huobi API
 *
 * API version: 0.1
 * Contact: qishiwenjun@163.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package huobiapi
// ModelsComponent struct for ModelsComponent
type ModelsComponent struct {
	CreatedAt string `json:"created_at,omitempty"`
	Description string `json:"description,omitempty"`
	Group bool `json:"group,omitempty"`
	GroupId string `json:"group_id,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	OnlyShowIfDegraded bool `json:"only_show_if_degraded,omitempty"`
	PageId string `json:"page_id,omitempty"`
	Position int32 `json:"position,omitempty"`
	Showcase bool `json:"showcase,omitempty"`
	Status string `json:"status,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
