/*
 * Huobi API
 *
 * Huobi API
 *
 * API version: 0.1
 * Contact: qishiwenjun@163.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package huobiapi
// ModelsSystemStatus struct for ModelsSystemStatus
type ModelsSystemStatus struct {
	Description string `json:"description,omitempty"`
	Indicator string `json:"indicator,omitempty"`
}
