/*
 * Huobi API
 *
 * Huobi API
 *
 * API version: 0.1
 * Contact: qishiwenjun@163.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package huobiapi
// ModelsResponseV1 struct for ModelsResponseV1
type ModelsResponseV1 struct {
	Data map[string]interface{} `json:"data,omitempty"`
	Status string `json:"status,omitempty"`
}
