/*
 * Huobi API
 *
 * Huobi API
 *
 * API version: 0.1
 * Contact: qishiwenjun@163.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package huobiapi
// ModelsResponse struct for ModelsResponse
type ModelsResponse struct {
	Code int32 `json:"code,omitempty"`
	Data map[string]interface{} `json:"data,omitempty"`
	Message string `json:"message,omitempty"`
}
