openapi: 3.0.1
info:
  contact:
    email: qishiwenjun@163.com
    name: Turing Zhu
  description: Huobi API
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  title: Huobi API
  version: "0.1"
servers:
- url: https://api.testnet.huobi.pro/
paths:
  /v1/common/timestamp:
    get:
      description: This endpoint returns the current timestamp, i.e. the number of
        milliseconds that have elapsed since 00:00:00 UTC on 1 January 1970.
      operationId: TimestampV1
      responses:
        "200":
          content:
            application/json:
              schema:
                type: integer
          description: OK
      summary: Get Current Timestamp
      tags:
      - Reference Data
components:
  schemas: {}
